# Generated by Django 3.0.8 on 2020-08-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Internship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_3',
        ),
    ]
