# Generated by Django 3.0.8 on 2020-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog', '0002_auto_20200801_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Account_No',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Debit_Card_No',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cvv',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
