# Generated by Django 3.0.8 on 2020-08-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog', '0003_auto_20200801_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Exp_Date',
            field=models.DateField(null=True),
        ),
    ]
