# Generated by Django 3.0.8 on 2020-08-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog', '0005_auto_20200801_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Chit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Account_No', models.CharField(max_length=200, null=True)),
                ('Debit_Card_No', models.CharField(max_length=200, null=True)),
                ('Exp_Date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
